{% set version = "3.09" %}

package:
  name: bullet
  version: {{ version }}

source:
  fn: bullet3-{{ version }}.tar.gz
  url: https://github.com/bulletphysics/bullet3/archive/{{ version }}.tar.gz
  sha256: f2feef9322329c0571d9066fede2db0ede92b19f7f7fdf54def3b4651f02af03
  patches:
    - add_rt.patch  # [linux]

build:
  number: 0

outputs:
  - name: bullet-cpp
    script: build_cpp.sh    # [unix]
    script: bld_cpp.bat     # [win]
    build:
      run_exports:
        - "{{ pin_subpackage('bullet-cpp', max_pin='x.x.x' )}}"

    requirements:
      build:
        - cmake
        - ninja
        - '{{ compiler("c") }}'
        - '{{ compiler("cxx") }}'
        - "{{ cdt('mesa-libgl-devel') }}"  # [linux]
        - "{{ cdt('mesa-dri-drivers') }}"  # [linux]
      host:
        - xorg-libx11    # [unix]
        - xorg-libxext   # [unix]
        - python
        - numpy
      run:
        - xorg-libx11   # [unix]
        - xorg-libxext  # [unix]

  - name: pybullet
    script: build_py.sh   # [unix]
    script: bld_py.bat    # [win]
    requirements:
      build:
        - cmake
        - ninja
        - '{{ compiler("c") }}'
        - '{{ compiler("cxx") }}'
      host:
        - '{{ pin_compatible("bullet-cpp", exact=True) }}'
        - python
        - numpy
      run:
        - '{{ pin_compatible("bullet-cpp", exact=True) }}'
        - python
        - numpy
    test:
      imports:
        - pybullet

  - name: bullet
    script:
      - echo "Building"
    requirements:
      run:
        - '{{ pin_compatible("bullet-cpp", exact=True) }}'
        - '{{ pin_compatible("pybullet", exact=True) }}'

about:
  home: http://bulletphysics.org
  license: Zlib
  license_file: LICENSE.txt
  summary: Bullet Physics SDK real-time collision detection and multi-physics simulation for VR, games, visual effects, robotics, machine learning etc.

extra:
  recipe-maintainers:
    - xantares
    - wolfv