travis:
  secure:
    BINSTAR_TOKEN: VePx9+1zSlqY+ymBAvreKcXAvXARdfdsYseS3c9vqb0roAtb8aTNAZJi9ub6ChVq1XDG4dStJ79q9rBZpq00Tr57Ixz68C7S/TNhFOPlyYwXGO6rWCtXa7KtEzD9CvSVFNJ+eExyOfhok/Y3FK94iAA18Pgz3zNh9KeoY0MVetx1eHdRA7JchfUQUS31+06B+OISGvwdMeN4e3FxXqBmZV8uInSvefUoC0e5GMBrhMN0WhE8qpSzThPNzwTPIupfQQQPQqX7fa2jFCbw1mcffQQeV1YdovDHxXgUQ3PbK6ykQoIiB3d/3uoQMZ+BWSh3cdltu/IMe8Lh24+lN9LhpTWec1m5vnp/cExwMCjLJgV47djravpwsuHxtzroj25UD/SywMUnAe1k7ZDPD4+H6+2JIhZCltRs3FyrrMp6tZ6Q8IQGaebZHb0nLmvsY3LtoThTLu7SYl49bmvpICd/OtWQl1kon5Z9/jvPj7x7trErFxjEUYnK7EdL29cfPnl78pOjiT8YzcKxdyr5MRKWMGQEg2XnaOmGxwHqeKtjRcbOuXNJHBOMtVEiYaXaHgpa3YIAsKAJG7/nAybO0iJCILzka1OdRmKdsR/YG+Idz7pyry2V8sWwGYO7L9mF+Y09RVgYBK+3CKJFTV9kLr1fc8snsjatTLL2qDzl6yyQEF4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
